---
- hosts: routers
  tasks:
    - name: "TASK 1: Apply device configurations using SSH/CLI"
      ios_config:
        src: "configs_build/{{ inventory_hostname }}.txt"
      notify: config_changed
      register: cli_result


  handlers:
    - name: "HANDLER 1: Display relevant changes"
      listen: config_changed
      debug:
        msg: "{{ cli_result.commands }}"


    - name: "HANDLER 2: Wait 10 seconds for convergence"
      listen: config_changed
      pause:
        seconds: 10

- name: "PLAY 1: Check pings on PE2"
  hosts: PE1
  tasks:
    - name: "TASK 1: Ping PE2"
      ios_ping:
        dest: 2.2.2.2
- name: "PLAY 2: Check pings on PE3"
  hosts: PE1
  tasks:
    - name: "TASK 1: Ping PE3"
      ios_ping:
        dest: 3.3.3.3
- name: "PLAY 3: Check pings on PE4"
  hosts: PE1
  tasks:
    - name: "TASK 1: Ping PE4"
      ios_ping:
        dest: 4.4.4.4